export const bookshelf: string[] = [
  "The American Bee Journal",
  "IT Agraria",
  "Popular Science Monthly",
  "Bird-Lore",
  "Journal of Entomology and Zoology",
  "Garden and Forest",
  "Animals-Wild-Reptiles and Amphibians",
  "Mother Earth",
  "Birds, Illustrated by Color Photography",
  "Microbiology",
  "Mycology",
  "Northern Nut Growers Association",
  "Prairie Farmer",
  "The Botanical Magazine",
  "Animals-Wild-Insects",
  "PT Ciência e Técnica",
  "Astronomy",
  "Microscopy",
  "IT Botanica",
  "Animals-Wild-Trapping",
  "Ecology",
  "Animals-Wild",
  "Animals-Wild-Birds",
  "Chemistry",
  "Science",
  "Animals-Domestic",
  "Forestry",
  "Scientific American",
  "IT Scienza",
  "Zoology",
  "Natural History",
  "Animal",
  "Animals-Wild-Mammals",
  "Biology",
  "Physics",
  "FR Sciences et Techniques",
  "Horticulture",
  "Botany",
  "Geology",
] as const;
