export const bookshelf: string[] = [
  "The Catholic World",
  "The Irish Ecclesiastical Record",
  "The Church of England Magazine",
  "The Baptist Magazine",
  "The Christian Foundation",
  "The Menorah Journal",
  "Atheism",
  "IT Religione e Spiritualità",
  "Bahá'í Faith",
  "The National Preacher",
  "Buddhism",
  "Latter Day Saints",
  "The American Missionary",
  "Hinduism",
  "FR Occultisme",
  "FR Philosophie, Religion et Morale",
  "Paganism",
  "Children's Religion",
  "Judaism",
  "Islam",
  "Christianity",
] as const;
