export const bookshelf: string[] = [
  "Child's Own Book of Great Musicians",
  "Our Young Folks",
  "Harper's Young People",
  "Barnavännen",
  "Little Folks",
  "The Girls Own Paper",
  "IT Letteratura per ragazzi",
  "Mrs Whittelsey's Magazine for Mothers and Daughters",
  "Golden Days for Boys and Girls",
  "PT Infantil e Juvenil",
  "Scouts",
  "St. Nicholas Magazine for Boys and Girls",
  "The Nursery",
  "Dew Drops",
  "DE Kinderbuch",
  "Children's Anthologies",
  "Children's Verse",
  "Children's Picture Books",
  "Children's Fiction",
  "FR Jeunesse",
  "Children's Literature",
  "Children's Book Series",
  "School Stories",
  "Punchinello",
] as const;
