export const bookshelf: string[] = [
  "FR Nouveautés",
  "IT Miscellanea",
  "FR Chroniques",
  "FR Prix Nobel",
  "Project Gutenberg",
  "IT Cucina",
  "The Scrap Book",
  "The Contemporary Review",
  "Ainslee's",
  "IT Numismatica",
  "Armour's Monthly Cook Book",
  "Celtic Magazine",
  "Harper's New Monthly Magazine",
  "PT Periódicos",
  "Donahoe's Magazine",
  "The Arena",
  "FR Métiers et Artisanat",
  "The Philatelic Digital Library Project",
  "IT Umorismo",
  "FR Musique",
  "The Unpopular Review",
  "FR Séduction et libertinage",
  "Continental Monthly",
  "The International Magazine of Literature, Art, and Science",
  "Music",
  "FR Femmes",
  "FR Humour",
  "Woodwork",
  "FR Sports et loisirs",
  "Reference",
  "FR Presse",
  "FR Nouvelles",
  "Crime Nonfiction",
  "Contemporary Reviews",
  "FR Chansons",
  "Humor",
  "Christmas",
  "DE Sachbuch",
  "Bestsellers, American, 1895-1923",
  "IT Musica",
  "Movie Books",
  "Bibliomania",
  "Cookbooks and Cooking",
  "Best Books Ever Listings",
  "Banned Books from Anne Haight's list",
  "Banned Books List from the American Library Association",
] as const;
