export const bookshelf: string[] = [
  "General Fiction",
  "Romantic Fiction",
  "IT Narrativa varia",
  "The Galaxy",
  "Astounding Stories",
  "IT Romanzi storici",
  "The Argosy",
  "PT Contos",
  "PT Romance",
  "Mystery Fiction",
  "Love",
  "Erotic Fiction",
  "FR Science fiction",
  "Science Fiction by Women",
  "FR Contes",
  "Crime Fiction",
  "Historical Fiction",
  "IT Racconti",
  "Precursors of Science Fiction",
  "Adventure",
  "IT Romanzi",
  "Pirates, Buccaneers, Corsairs, etc.",
  "Short Stories",
  "Detective Fiction",
  "Western",
  "Gothic Fiction",
  "Horror",
  "Science Fiction",
  "Fantasy",
] as const;
