export const bookshelf: string[] = [
  "Maps and Cartography",
  "IT Geografia",
  "Norway",
  "Czech",
  "South America",
  "FR Villes",
  "Bulletin de Lille",
  "CIA World Factbooks",
  "The Bay State Monthly",
  "Bulgaria",
  "De Aarde en haar Volken",
  "Argentina",
  "France",
  "India",
  "New Zealand",
  "Egypt",
  "United Kingdom",
  "South Africa",
  "Africa",
  "Australia",
  "Greece",
  "Canada",
  "Germany",
  "United States",
  "Native America",
  "Italy",
] as const;
