export const bookshelf: string[] = [
  "Poetry, A Magazine of Verse",
  "The Yellow Book",
  "Scribner's Magazine",
  "IT Teatro dialettale",
  "Graham's Magazine",
  "The Esperantist",
  "The American Quarterly Review",
  "FR Livres, Collections et Bibliophilie",
  "The Writer",
  "IT Linguistica",
  "The Mirror of Taste, and Dramatic Censor",
  "The Idler",
  "IT Letteratura",
  "The Knickerbocker",
  "IT Teatro in prosa",
  "PT Teatro",
  "IT Teatro in versi",
  "PT Poesia",
  "The Aldine",
  "Godey's Lady's Book",
  "PT Língua Portuguesa",
  "Early English Text Society",
  "Chambers's Edinburgh Journal",
  "FR Langues",
  "Lippincott's Magazine",
  "Blackwood's Edinburgh Magazine",
  "Esperanto",
  "DE Lyrik",
  "Notes and Queries",
  "FR Théâtre",
  "German Language Books",
  "6 Best Loved Spanish Literary Classics",
  "DE Prosa",
  "One Act Plays",
  "African American Writers",
  "Punch",
  "Poetry",
  "The Atlantic Monthly",
  "FR Poésie",
  "FR Littérature francophone",
  "DE Drama",
  "FR Littérature",
  "Harvard Classics",
  "The Mirror of Literature, Amusement, and Instruction",
  "The Strand Magazine",
  "IT Poesia",
  "Plays",
] as const;
